apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginx-deployment-csi-provider
spec:
  provider: akeyless
  parameters:
    akeylessGatewayURL: "https://api.akeyless.io"
    akeylessAccessID: "<your access id>"
    akeylessAccessKey: "<your access key - NOT FOR PRODUCTION>"
    akeylessAccessType: "access_key"
    objects:  |
      - secretPath: "/full/path/to/secret/item"
        fileName: "local-secret-filename"
      - secretPath: "/full/path/to/certificate/item"
        fileName: "local-certificate-filename"
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-deployment
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "nginx-deployment-csi-provider"
